spring:
  main:
    banner-mode: console
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-root.xml
    contexts: DEV
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
#logging:
#  file:
#    name: hw09.log
#  pattern:
#    console: