DELETE http://localhost:8080/book/1
Accept: application/json

###
PUT http://localhost:8080/book/1
Content-Type: application/json

{
  "title": "new book",
  "author": {
    "authorId": 1,
    "authorName" : "Пушкин А"
  },
  "genre" : {
    "genreId" : 1,
    "genreName" : "Roman"
  }
}

###

POST http://localhost:8080/book
Content-Type: application/json

{
  "title": "new book",
  "author": {
    "authorId": 1,
    "authorName" : "Пушкин А"
  },
  "genre" : {
    "genreId" : 1,
    "genreName" : "Roman"
  }
}

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "title" : "new book",
  "authorId" : 5,
  "genreId" : 5
}

###
GET http://localhost:8080/book/5
Accept: application/json

###
GET http://localhost:8080/book/4
Accept: application/json

###
GET http://localhost:8080/book/
Accept: application/json

###
